### ISSUE TITLE
Question about the Inference Stage

### ISSUE THREAD

**Issue by YixiangCh** [med-air/PICG2scoring#1]
Very amazing project! I still have some doubts about whether your model only uses "Scoring Network" for classification and discard "Guideline Network" in inference stage? Thanks.

**Comment by ztt0821** [comment]
> Very amazing project! I still have some doubts about whether your model only uses "Scoring Network" for classification and discard "Guideline Network" in inference stage? Thanks.

Thank you very much for your attention to our work. Your understanding is correct - we only need the guideline network during training. During inference, only the scoring network is required.

**Comment by YixiangCh** [comment]
Thanks for your answer!
